### ISSUE TITLE
Функционал составление смет проектов

### ISSUE THREAD

**Issue by syeysk** [TVP-Support/activista#23]
**Опишите проблему в общем**
При старте новых проектов людям сложно составлять сметы: есть непонимание, что именно в них указывать, в каком порядке. 

**Как повторить:**
Запустить новый проект и посмотреть на боль тех, кто составляет смету)

**Предполагаемые направления решений**

Сделать модуль в приложении activista для составления смет и привязки их к проектам.

В смете указывать:
- к какому проекту относится смета
- список отсутствующих ресурсов (для чего используется в проекте, их значимость ("критически важная", "можно обойтись") и так далее)
- список имеющихся ресурсов
- финансовый расходы и т. д.

**Comment by redboo** [comment]
Дублирует #22
